[package]
name = "ems-backend"
version = "0.1.0"
edition = "2021"
authors = ["Smart Wattanapornmongkol <smartwattana@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
uuid = { version = "1.9.1", features = ["serde", "v4"] }
actix-cors = "0.7.0"
actix-web = "4.8.0"
async-trait = "0.1.80"
bs58 = "0.5.1"
chrono = { version = "0.4.38", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.11.3"
futures = "0.3.30"
jsonwebtoken = "9.3.0"
log = "0.4.22"
rand = "0.8.5"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.203"
serde_json = "1.0.118"
serde_qs = "0.13.0"
sha2 = "0.10.8"
parking_lot = "0.12.3"
sqlx = { version = "0.8.3", features = [
    "chrono",
    "json",
    "macros",
    "postgres",
    "runtime-tokio-native-tls",
    "uuid",
] }
mysk-lib = { path = "./dep/mysk-api/mysk-lib" }
mysk-lib-macros = { path = "./dep/mysk-api/mysk-lib-macros" }
mysk-lib-derives = { path = "./dep/mysk-api/mysk-lib-derives" }
